---
version: "3.5"
services:
  openssh-server-ubuntu20.04:
    image: webrtc:1.0
    container_name: webrtc
    hostname: openssh-server #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SUDO_ACCESS=true # ssh optional
      - PASSWORD_ACCESS=true # ssh optional
      - USER_PASSWORD=canhthong # ssh optional
      - USER_NAME=admin # ssh optional
      - HOST=0.0.0.0 # listen public ip - very importance
    volumes:
      - ./volume:/config # for ssh config
      - ./webrtc/full.pem:/root/full.pem # all in one: key-private, cert file(public key), and bundle file
      - ./webrtc/key.pem:/root/key.pem
      - ./webrtc/constants.py:/root/app_engine/constants.py # for all config of apprtc project
    ports:
      - 2222:2222
      - 5443:8443
      - 5442:8442
      - 5000:8000
    restart: unless-stopped
